// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./../src/components/AlertDialog/index.vue')['default']
    AutoScroll: typeof import('./../src/components/AutoScroll/index.vue')['default']
    ConTable: typeof import('./../src/components/ConTable/index.vue')['default']
    CountTo: typeof import('./../src/components/CountTo/index.vue')['default']
    CustomTable: typeof import('./../src/components/CustomTable/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FormDialog: typeof import('./../src/components/FormDialog/index.vue')['default']
    IconDropDown: typeof import('./../src/components/IconDropDown/index.vue')['default']
    InfoDialog: typeof import('./../src/components/InfoDialog/index.vue')['default']
    LayerInfoDialog: typeof import('./../src/components/LayerInfoDialog/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowTab: typeof import('./../src/components/Tab/rowTab.vue')['default']
    Tab: typeof import('./../src/components/Tab/index.vue')['default']
    Table: typeof import('./../src/components/Table/index.vue')['default']
    TableInfo: typeof import('./../src/components/TableInfo/index.vue')['default']
    VideoPlayer: typeof import('./../src/components/VideoPlayer/index.vue')['default']
    WebViewPage: typeof import('./../src/components/WebViewPage/index.vue')['default']
  }
}
